import type { ImageMeta } from "./types";

export const appImages = {
  "app-super-identifier": {
    id: "app-super-identifier",
    src: "images/applications/super-identifier-labels.webp",
    width: 268,
    height: 200,
    title: "One super identifier",
    shortCopy: "One super identifier",
    alt: "Stacked UPS, DHL, and FedEx Express shipping labels. The FedEx Large Pak label shows From: PAC-987-654-3210-XYZ and To: PAC-123-456-7890-QTR.",
    caption: "Carrier labels that can carry one zz-Code ID.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["applications"],
    status: "concept",
    sourceTag: "MICHAEL",
  },
  "app-postage-letters": {
    id: "app-postage-letters",
    src: "images/applications/postage-three-letters.webp",
    width: 712,
    height: 530,
    title: "Handwritten postage codes",
    shortCopy: "Handwritten postage codes",
    alt: "Three envelopes. One shows a long code, PAC-987-654-3210-RSR. One has zz-USPS-123456789-UK in the stamp area. One has zz-hat-more-921 handwritten above the address.",
    caption:
      "Three letters, three ways a zz-code could serve as postage (concept).",
    focal: { x: 0.5, y: 0.5 },
    destination: ["applications"],
    status: "concept",
    sourceTag: "MICHAEL",
  },
  "app-delivery-overview": {
    id: "app-delivery-overview",
    src: "images/applications/delivery-overview.webp",
    width: 837,
    height: 1042,
    title: "All four steps",
    shortCopy: "All four steps",
    alt: "Four panels: a woman orders on her phone, a warehouse worker handles a box labeled zz-apple-sky-5678-zz, a courier carries the box from a van, and a customer collects it at a pickup counter.",
    caption: "Purchase, fulfillment, last mile, and pickup.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["applications"],
    status: "concept",
    sourceTag: "MICHAEL",
  },
  "app-delivery-1": {
    id: "app-delivery-1",
    src: "images/applications/delivery-1-purchase.webp",
    width: 337,
    height: 422,
    title: "Purchase",
    shortCopy: "Purchase",
    alt: "A woman on a sofa orders on her phone. A panel beside her shows a cart, a shoe, and a delivery option switched on.",
    caption: "Purchase: Customer selects reduced-exposure delivery.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["applications"],
    status: "concept",
    sourceTag: "MICHAEL",
  },
  "app-delivery-2": {
    id: "app-delivery-2",
    src: "images/applications/delivery-2-fulfillment.webp",
    width: 340,
    height: 421,
    title: "Fulfillment",
    shortCopy: "Fulfillment",
    alt: "A warehouse worker in gloves handles a box on a conveyor. The box label reads zz-apple-sky-5678-zz.",
    caption: "Fulfillment: The parcel displays only a shipment reference.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["applications"],
    status: "concept",
    sourceTag: "MICHAEL",
  },
  "app-delivery-3": {
    id: "app-delivery-3",
    src: "images/applications/delivery-3-last-mile.webp",
    width: 337,
    height: 425,
    title: "Last mile",
    shortCopy: "Last mile",
    alt: "A courier beside a delivery van checks his phone while holding a box labeled zz-apple-sky-5678-zz.",
    caption:
      "Last mile: The assigned courier receives task-limited address access.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["applications"],
    status: "concept",
    sourceTag: "MICHAEL",
  },
  "app-delivery-4": {
    id: "app-delivery-4",
    src: "images/applications/delivery-4-pickup.webp",
    width: 340,
    height: 425,
    title: "Pickup",
    shortCopy: "Pickup",
    alt: "A customer holds up her phone at a pickup counter while a staff member hands over a box labeled zz-apple-sky-5678-zz.",
    caption:
      "Pickup: A private credential authorizes release at a secure pickup point.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["applications"],
    status: "concept",
    sourceTag: "MICHAEL",
  },
  "app-wallet-ens": {
    id: "app-wallet-ens",
    src: "images/applications/wallet-ens-alias.webp",
    width: 733,
    height: 436,
    title: "Wallet address",
    shortCopy: "Wallet address",
    alt: "An acrylic desk sign reading zz-vitalik.eth-zz, Wallet / Contact Code, with a QR code. A phone shows the zzthis app with zz-vitalik.eth-zz marked Verified and options to connect a wallet, add the address, save the contact, verify on-chain, and pay or tip.",
    caption:
      "An Ethereum ENS address being scanned by a wallet with a zzThis function.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["applications"],
    status: "concept",
    sourceTag: "MICHAEL",
  },
  "app-for-sale": {
    id: "app-for-sale",
    src: "images/applications/for-sale-lamp.webp",
    width: 590,
    height: 488,
    title: "For sale",
    shortCopy: "For sale",
    alt: "A table lamp with a handwritten paper tag reading zz-1234ABCD-zz, under a For Sale banner.",
    caption: "A zz-code attached to a lamp (object) for sale.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["applications"],
    status: "concept",
    sourceTag: "MICHAEL",
  },
  "app-help-wanted": {
    id: "app-help-wanted",
    src: "images/applications/help-wanted-sign.webp",
    width: 595,
    height: 492,
    title: "Help wanted",
    shortCopy: "Help wanted",
    alt: "A handwritten HELP WANTED sign on a glass door with zz-1234ABCD-zz written below.",
    caption: "A help wanted sign with the zz-code.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["applications"],
    status: "concept",
    sourceTag: "MICHAEL",
  },
  "app-event-cancelled": {
    id: "app-event-cancelled",
    src: "images/applications/event-cancelled-sign.webp",
    width: 618,
    height: 421,
    title: "Event cancelled",
    shortCopy: "Event cancelled",
    alt: "A handwritten EVENT CANCELLED sign reading zz-123XYZ-zz on a door. A phone beside it shows the zzthis app: Code recognized, Event Update, Event Cancelled.",
    caption: "An “Event Cancelled” sign with the zz-code.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["applications"],
    status: "concept",
    sourceTag: "MICHAEL",
  },
  "app-connect": {
    id: "app-connect",
    src: "images/applications/connect-guest-wifi.webp",
    width: 293,
    height: 328,
    title: "Connect",
    shortCopy: "Connect",
    alt: "A table sign reading zz Guest WiFi connect zz with a Wi-Fi icon. A phone shows the zzthis app opening the guest Wi-Fi details.",
    caption: "A sign code opens guest Wi-Fi details.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["applications"],
    status: "concept",
    sourceTag: "MICHAEL",
  },
  "app-shop-pay": {
    id: "app-shop-pay",
    src: "images/applications/shop-pay-booth.webp",
    width: 294,
    height: 327,
    title: "Shop / Pay",
    shortCopy: "Shop / Pay",
    alt: "A table sign reading zz Maria flea market booth 12 zz. A phone shows the zzthis app opening the vendor page with items, a pay link, and contact.",
    caption: "A booth code opens the vendor page.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["applications"],
    status: "concept",
    sourceTag: "MICHAEL",
  },
  "app-donate": {
    id: "app-donate",
    src: "images/applications/donate-booth.webp",
    width: 291,
    height: 333,
    title: "Donate",
    shortCopy: "Donate",
    alt: "A table sign reading zz Hacker Dojo donate 11 zz. A phone shows the zzthis app opening a donation page.",
    caption: "A sign code opens a donation page.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["applications"],
    status: "concept",
    sourceTag: "MICHAEL",
  },
  "app-trail-marker": {
    id: "app-trail-marker",
    src: "images/applications/trail-marker.webp",
    width: 812,
    height: 431,
    title: "Trail marker",
    shortCopy: "Trail marker",
    alt: "A wooden trail sign reading zz-TrailInfo-zz, Trail Info Code, with a hiker nearby. A phone shows the zzthis app with trail updates, a check-in, a safety alert, and a map.",
    caption:
      "A trail marker tags in the park that visitors can scan and update with their posts, etc.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["applications"],
    status: "concept",
    sourceTag: "MICHAEL",
  },
  "app-share": {
    id: "app-share",
    src: "images/applications/share-infographic.webp",
    width: 368,
    height: 481,
    title: "Share",
    shortCopy: "Share",
    alt: "Infographic titled Share: readable short codes for everyday sharing. Example codes: zz Alex photos wedding zz, zz Maya resume zz, zz Sam playlist zz.",
    caption: "Wedding photos and other everyday sharing with a zz-code.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["applications"],
    status: "concept",
    sourceTag: "MICHAEL",
  },
  "app-community": {
    id: "app-community",
    src: "images/applications/community-infographic.webp",
    width: 389,
    height: 480,
    title: "Community",
    shortCopy: "Community",
    alt: "Infographic titled Community: make flyers actionable without forcing a QR code. A lost dog flyer and a block party sign, with codes zz Lost dog maple street zz, zz Block party RSVP zz, and zz Free couch pickup zz.",
    caption: "Lost dog and block party signs with a zz-code.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["applications"],
    status: "concept",
    sourceTag: "MICHAEL",
  },
  "app-handwritten-works": {
    id: "app-handwritten-works",
    src: "images/applications/handwritten-works-infographic.webp",
    width: 394,
    height: 482,
    title: "Handwritten works",
    shortCopy: "Handwritten works",
    alt: "Infographic titled Handwritten works: no printer, no QR generator, just write the code. Signs for a lemonade stand, a garage sale, and a lost cat, with codes zz Lemonade stand pay zz, zz Garage sale map zz, and zz Lost cat help zz.",
    caption: "Lemonade stand and lost cat signs with a zz-code.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["applications"],
    status: "concept",
    sourceTag: "MICHAEL",
  },
  "app-tape-before": {
    id: "app-tape-before",
    src: "images/applications/business-tape-before.webp",
    width: 395,
    height: 300,
    title: "Before",
    shortCopy: "Before",
    alt: "Before: yellow company tape on a red post reading 510-786-2004, Western States Tool & Supply, 1950 Alpine Way, Hayward, CA 94545.",
    caption: "Before: product tape with a phone number.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["applications"],
    status: "real-photo",
    sourceTag: "MICHAEL",
  },
  "app-tape-after": {
    id: "app-tape-after",
    src: "images/applications/business-tape-after.webp",
    width: 425,
    height: 278,
    title: "After",
    shortCopy: "After",
    alt: "After, with the banner After with UZZ / zzthis: the same yellow tape now reads zz@-WESTERN-STATES-zz, Tool & Supply, 1950 Alpine Way, Hayward, CA 94545.",
    caption: "After: the same tape with a scannable zz-Code.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["applications"],
    status: "real-photo",
    sourceTag: "MICHAEL",
  },
  "app-truck-before": {
    id: "app-truck-before",
    src: "images/applications/truck-sign-before.webp",
    width: 342,
    height: 281,
    title: "Before",
    shortCopy: "Before",
    alt: "Before: a box truck with Filco Logistics LLC signage, Professional Moving & Staging Transport, and a partly blurred phone number.",
    caption: "Before: printed company signage on a cargo truck.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["applications"],
    status: "real-photo",
    sourceTag: "MICHAEL",
  },
  "app-truck-after": {
    id: "app-truck-after",
    src: "images/applications/truck-sign-after.webp",
    width: 342,
    height: 280,
    title: "After",
    shortCopy: "After",
    alt: "After: the same truck signage with a capital-letter zz mark added before the phone number 650-460.",
    caption:
      "After: a zz mark added so people can scan it for the information.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["applications"],
    status: "real-photo",
    sourceTag: "MICHAEL",
  },
} satisfies Record<string, ImageMeta>;
