import { appImages } from "./appImages";
import type { ImageMeta } from "./types";

export const images = {
  a: {
    id: "a",
    src: "images/panels/a-duffels-crate.webp",
    width: 1600,
    height: 900,
    title: "No device, no network: mark first",
    shortCopy: "No device, no network: mark first",
    alt: "Olive duffels and a crate with blue tape marked zz-b2-smith-1-zz and zz-b2-4-zz.",
    caption:
      "With only a marker, a Soldier names and marks each item with a self-made field code when no phone, scanner, or network is available, then reconciles it to the system later. Built for the extreme edge, and fault tolerant.",
    focal: { x: 0.5, y: 0.6 },
    destination: ["home", "applications"],
    status: "concept",
    sourceTag: "BRIEF",
  },
  b: {
    id: "b",
    src: "images/panels/b-crate-word-code.webp",
    width: 1600,
    height: 900,
    title: "Hero photo",
    shortCopy: "Crate and damaged inventory label; visible handwritten code.",
    alt: "Olive crate with blue tape reading zz-copper-lantern-sky-zz beside an obscured barcode.",
    caption: "Word code on blue tape beside an obscured barcode.",
    focal: { x: 0.5, y: 0.55 },
    destination: ["home", "demo"],
    status: "concept",
    sourceTag: "BRIEF",
  },
  "alt-b": {
    id: "alt-b",
    src: "images/panels/alt-b-weathered-crate.webp",
    width: 1600,
    height: 900,
    title: "Unreadable barcode? Mark it by hand",
    shortCopy: "Unreadable barcode? Mark it by hand",
    alt: "Weathered crate label with a handwritten blue-tape code over a barcode.",
    caption:
      "When an existing barcode or QR code is damaged or cannot be read, a Soldier writes a zz-code next to it in seconds, and the item is logged into the system.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "applications"],
    status: "concept",
    sourceTag: "WIRE",
  },
  c: {
    id: "c",
    src: "images/panels/c-pallet-circled.webp",
    width: 1600,
    height: 900,
    title: "Batched pallet: many items, one code",
    shortCopy: "Batched pallet: many items, one code",
    alt: "Wrapped pallet hand-printed with (zz) camp bravo four two (zz).",
    caption:
      "Loose items, with or without their own labels, are photographed and batched under one code or work order: here, a wrapped pallet with a circled zz marker.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "applications"],
    status: "concept",
    sourceTag: "BRIEF",
  },
  "alt-c": {
    id: "alt-c",
    src: "images/panels/alt-c-circled-tape.webp",
    width: 1600,
    height: 664,
    title: "Mark",
    shortCopy: "Write on tape or an item.",
    alt: "Close-up of blue tape reading (zz) camp bravo four two (zz).",
    caption: "Write on tape or an item.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "how"],
    status: "concept",
    sourceTag: "WIRE",
  },
  d: {
    id: "d",
    src: "images/panels/d-camera-read.webp",
    width: 1600,
    height: 900,
    title: "Read",
    shortCopy: "Camera or manual entry.",
    alt: "Phone camera framing a handwritten crate code with offline and check word indicators.",
    caption: "Camera or manual entry.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "how", "applications"],
    status: "concept",
    sourceTag: "WIRE",
  },
  e: {
    id: "e",
    src: "images/panels/e-linked-record.webp",
    width: 1600,
    height: 800,
    title: "Link",
    shortCopy: "Connect to a record.",
    alt: "Tablet record card linking a code to NSN, document number, hand receipt, and photo.",
    caption: "Code linked to NSN, document number, hand receipt, and photo.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "how", "applications"],
    status: "concept",
    sourceTag: "BRIEF",
  },
  f: {
    id: "f",
    src: "images/panels/f-radio-readback.webp",
    width: 1600,
    height: 900,
    title: "Report",
    shortCopy: "Say code words when useful.",
    alt: 'Two radios with the handoff "Tag: copper, lantern, sky. Break." and a read-back.',
    caption: "Radio cue and read-back: three code words.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "how", "applications"],
    status: "concept",
    sourceTag: "BRIEF",
  },
  g: {
    id: "g",
    src: "images/panels/g-parcel.webp",
    width: 1600,
    height: 900,
    title: "Postal and parcel",
    shortCopy: "Handwritten code on a parcel.",
    alt: "Parcel with zz-river-maple-sky-zz handwritten beside the address.",
    caption: "Handwritten code on a parcel beside the address.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "applications"],
    status: "concept",
    sourceTag: "BRIEF",
  },
  h: {
    id: "h",
    src: "images/panels/h-lost-cat.webp",
    width: 1600,
    height: 902,
    title: "Everyday and community",
    shortCopy: "Lost-cat flyer.",
    alt: "Lost-cat flyer with zz-kathy-lost-cat-zz being scanned by a phone.",
    caption: "Lost-cat flyer with handwritten code.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "applications"],
    status: "concept",
    sourceTag: "BRIEF",
  },
  i: {
    id: "i",
    src: "images/panels/i-agent-alias.webp",
    width: 1600,
    height: 900,
    title: "Digital aliases",
    shortCopy: "Short agent alias.",
    alt: "Laptop showing a short zz alias mapped to a long agent address.",
    caption: "Short agent alias standing in for a long machine address.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "applications"],
    status: "concept",
    sourceTag: "BRIEF",
  },
  j: {
    id: "j",
    src: "images/panels/j-photo-to-action.webp",
    width: 1448,
    height: 1086,
    title: "Photograph",
    shortCopy: "Loose or broken items; spoken note.",
    alt: "Soldier photographing loose and broken items on a vehicle tailgate.",
    caption: "Loose or broken items; spoken note.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "how", "applications"],
    status: "concept",
    sourceTag: "WIRE",
  },
  k: {
    id: "k",
    src: "images/panels/k-ai-guidance.webp",
    width: 1448,
    height: 1086,
    title: "Guide",
    shortCopy: "Confirmed item and handling choices.",
    alt: "Rugged phone boxing each item with a proposed next step.",
    caption: "Confirmed item and handling choices.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "how", "applications", "demo"],
    status: "concept",
    sourceTag: "WIRE",
  },
  l: {
    id: "l",
    src: "images/panels/l-turn-in-form.webp",
    width: 1448,
    height: 1086,
    title: "Review",
    shortCopy: "Prepared form and photos.",
    alt: "Tablet turn-in request form with item fields and attached photos.",
    caption: "Prepared form and photos.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "how", "applications", "demo"],
    status: "concept",
    sourceTag: "WIRE",
  },
  m: {
    id: "m",
    src: "images/panels/m-shelf-inventory.webp",
    width: 1448,
    height: 1086,
    title: "Inventory assistant",
    shortCopy: "Same shelf across days.",
    alt: "Day 1 and Day 4 shelf photos; water at about two days left with a reorder prompt.",
    caption: "Same shelf across days; lower stock and proposed reorder.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "how", "applications"],
    status: "concept",
    sourceTag: "WIRE",
  },
  n: {
    id: "n",
    src: "images/panels/n-touch-first.webp",
    width: 1448,
    height: 1086,
    title: "Touch first",
    shortCopy: "Drag an identified item to an action.",
    alt: "Phone screen with a recognized item being dragged onto large action buttons.",
    caption: "Drag an identified item to an action; offer voice input.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "how", "applications"],
    status: "concept",
    sourceTag: "WIRE",
  },
  o: {
    id: "o",
    src: "images/panels/o-pack-and-ship.webp",
    width: 1448,
    height: 1086,
    title: "Pack and ship: no printer, no scale",
    shortCopy: "Photo in, packing guidance and parcel code out.",
    alt: "Phone packing guidance for a guitar and an appliance with a zz parcel code.",
    caption:
      "Take a photo of the item, such as a guitar or a blender; add a few spoken words or a photo of its label if you like. AI identifies it, estimates its weight, size, and postage, and shows how to pack it, or books a helper to pack it for you. You write the zz parcel code by hand.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "applications"],
    status: "concept",
    sourceTag: "BRIEF",
  },
  "demo-01": {
    id: "demo-01",
    src: "images/demo/01-crate-marked.webp",
    width: 1536,
    height: 1024,
    title: "Intro",
    shortCopy: "A field crate, marked by hand.",
    alt: "Field crate with a code handwritten on blue tape.",
    caption: "A field crate, marked by hand.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["demo"],
    status: "demo-mock",
    sourceTag: "ASSETS",
  },
  "demo-02": {
    id: "demo-02",
    src: "images/demo/02-crate-tape-closeup.webp",
    width: 1536,
    height: 1024,
    title: "Mark",
    shortCopy: "Write the code on tape.",
    alt: "Close-up of blue tape with a handwritten zz code.",
    caption: "Write the code on tape.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["demo"],
    status: "demo-mock",
    sourceTag: "ASSETS",
  },
  "demo-03": {
    id: "demo-03",
    src: "images/demo/03-crate-to-tablet.webp",
    width: 1536,
    height: 1024,
    title: "Linked",
    shortCopy: "Linked record (demo).",
    alt: "Marked crate beside a tablet showing its linked record.",
    caption: "Linked record (demo).",
    focal: { x: 0.5, y: 0.5 },
    destination: ["demo"],
    status: "demo-mock",
    sourceTag: "ASSETS",
  },
  "demo-04": {
    id: "demo-04",
    src: "images/demo/04-code-on-tablet-and-tape.webp",
    width: 1600,
    height: 800,
    title: "End",
    shortCopy: "Nothing was submitted.",
    alt: "The same zz code shown on a tablet screen and on tape.",
    caption: "Nothing was submitted.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["demo"],
    status: "demo-mock",
    sourceTag: "ASSETS",
  },
  "demo-05": {
    id: "demo-05",
    src: "images/demo/05-crate-handwritten-tape.webp",
    width: 1536,
    height: 1024,
    title: "Photo",
    shortCopy: "Photo taken (demo image).",
    alt: "Crate with a handwritten tape code, as photographed.",
    caption: "Photo taken (demo image).",
    focal: { x: 0.5, y: 0.5 },
    destination: ["demo"],
    status: "demo-mock",
    sourceTag: "ASSETS",
  },
  "hw-agent-notes": {
    id: "hw-agent-notes",
    src: "images/handwritten/hw-agent-notes.webp",
    width: 624,
    height: 827,
    title: "zz-ai@ agentsmith-zz",
    shortCopy: "Real photo.",
    alt: "Handwritten paper notes reading zz-patient name-zz, zz-ai@ agentsmith-zz, and zz dojo mojo glade-zz.",
    caption:
      "Real photo. “AI@” means the zz-code words link to an AI agent or resource that is authenticated and trustworthy.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["about"],
    status: "real-photo",
    sourceTag: "MICHAEL",
  },
  "hw-usps-tally": {
    id: "hw-usps-tally",
    src: "images/handwritten/hw-usps-tally.webp",
    width: 900,
    height: 1200,
    title: "zz- be bold be brave be beautiful-zz",
    shortCopy: "Real photo.",
    alt: "Handwritten page with an address sketch marked with a zz-usps-apple code, the line zz- be bold be brave be beautiful-zz, and a circled (zz) bravo code with four tally marks.",
    caption:
      "Real photo. Examples of nearly infinite forms: “USPS…” for postage; the others show more forms and uses.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["about"],
    status: "real-photo",
    sourceTag: "MICHAEL",
  },
  "hw-mark-on-object": {
    id: "hw-mark-on-object",
    src: "images/handwritten/hw-mark-on-object.webp",
    width: 900,
    height: 1200,
    title: "zz mark on an object",
    shortCopy: "Real photo.",
    alt: "A framed Flower Power print with a circled capital-letter zz sticker in the lower left and a handwritten zz note with a smiley in the lower right.",
    caption:
      "Real photo. To zz-register an object, thing, sign, or place for retrieval, mark it with a zz or (zz). It can then be recognized by people as scannable, and be scanned.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["about"],
    status: "real-photo",
    sourceTag: "MICHAEL",
  },
  "hw-dog-collar-tag": {
    id: "hw-dog-collar-tag",
    src: "images/handwritten/hw-dog-collar-tag.webp",
    width: 900,
    height: 1200,
    title: "zz tag on a dog collar",
    shortCopy: "Real photo.",
    alt: "A plush corgi wearing a round red collar tag marked with a capital-letter zz, to identify the dog.",
    caption:
      "Real photo. A zz tag on a dog collar shows the dog is zz-registered: give the zz app a photo of the dog, and its information can be retrieved.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["about"],
    status: "real-photo",
    sourceTag: "MICHAEL",
  },
  // [MICHAEL 2026-10-08] A pair below the real photos: the zz-Kathy-found-dog-zz
  // card, then the same card on a community board. Concept images, one shared
  // explainer (aboutPage.handwrittenPairCaption).
  "hw-kathy-found-dog": {
    id: "hw-kathy-found-dog",
    src: "images/handwritten/hw-kathy-found-dog.webp",
    width: 672,
    height: 655,
    title: "zz-Kathy-found-dog-zz",
    shortCopy: "Concept image.",
    alt: "A plush corgi with a round red zz collar tag, behind a hand-printed card reading zz-Kathy-found-dog-zz.",
    caption: "Concept image.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["about"],
    status: "concept",
    sourceTag: "MICHAEL",
  },
  "hw-kathy-community-board": {
    id: "hw-kathy-community-board",
    src: "images/handwritten/hw-kathy-community-board.webp",
    width: 680,
    height: 339,
    title: "zz-Kathy-found-dog-zz on a community board",
    shortCopy: "Concept image.",
    alt: "A store community board covered in notes, with the corgi photo and its zz-Kathy-found-dog-zz card pinned in the center.",
    caption: "Concept image.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["about"],
    status: "concept",
    sourceTag: "MICHAEL",
  },
  "logo-light": {
    id: "logo-light",
    src: "images/logos/zzthis-logo-on-light.webp",
    width: 464,
    height: 129,
    title: "zzThis",
    shortCopy: "zzThis",
    alt: "zzThis",
    caption: "",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "how", "applications", "about", "demo"],
    status: "logo",
    sourceTag: "ASSETS",
  },
  "logo-dark": {
    id: "logo-dark",
    src: "images/logos/zzthis-logo-on-dark.webp",
    width: 480,
    height: 140,
    title: "zzThis",
    shortCopy: "zzThis",
    alt: "zzThis",
    caption: "",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "how", "applications", "about", "demo"],
    status: "logo",
    sourceTag: "ASSETS",
  },
  ...appImages,
} satisfies Record<string, ImageMeta>;

export type ImageId = keyof typeof images;
