import type { ImageMeta } from "./types";

export const images = {
  a: {
    id: "a",
    src: "images/panels/a-duffels-crate.webp",
    width: 1600,
    height: 900,
    title: "No-device items",
    shortCopy: "No-device items",
    alt: "Olive duffels and a crate with blue tape marked zz-b2-smith-1-zz and zz-b2-4-zz.",
    caption: "No-device marking on duffels and a crate.",
    focal: { x: 0.5, y: 0.6 },
    destination: ["home", "applications"],
    status: "concept",
    sourceTag: "BRIEF",
  },
  b: {
    id: "b",
    src: "images/panels/b-crate-word-code.webp",
    width: 1600,
    height: 900,
    title: "Hero photo",
    shortCopy: "Crate and damaged inventory label; visible handwritten code.",
    alt: "Olive crate with blue tape reading zz-copper-lantern-sky-zz beside an obscured barcode.",
    caption: "Word code on blue tape beside an obscured barcode.",
    focal: { x: 0.5, y: 0.55 },
    destination: ["home", "demo"],
    status: "concept",
    sourceTag: "BRIEF",
  },
  "alt-b": {
    id: "alt-b",
    src: "images/panels/alt-b-weathered-crate.webp",
    width: 1600,
    height: 900,
    title: "Obscured label",
    shortCopy: "Obscured label",
    alt: "Weathered crate label with a handwritten blue-tape code over a barcode.",
    caption: "Obscured label.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "applications"],
    status: "concept",
    sourceTag: "WIRE",
  },
  c: {
    id: "c",
    src: "images/panels/c-pallet-circled.webp",
    width: 1600,
    height: 900,
    title: "Wrapped pallet",
    shortCopy: "Wrapped pallet",
    alt: "Wrapped pallet hand-printed with (zz) camp bravo four two (zz).",
    caption: "Wrapped mixed-goods pallet with circled zz marker.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "applications"],
    status: "concept",
    sourceTag: "BRIEF",
  },
  "alt-c": {
    id: "alt-c",
    src: "images/panels/alt-c-circled-tape.webp",
    width: 1600,
    height: 664,
    title: "Mark",
    shortCopy: "Write on tape or an item.",
    alt: "Close-up of blue tape reading (zz) camp bravo four two (zz).",
    caption: "Write on tape or an item.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "how"],
    status: "concept",
    sourceTag: "WIRE",
  },
  d: {
    id: "d",
    src: "images/panels/d-camera-read.webp",
    width: 1600,
    height: 900,
    title: "Read",
    shortCopy: "Camera or manual entry.",
    alt: "Phone camera framing a handwritten crate code with offline and checksum indicators.",
    caption: "Camera or manual entry.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "how", "applications"],
    status: "concept",
    sourceTag: "WIRE",
  },
  e: {
    id: "e",
    src: "images/panels/e-linked-record.webp",
    width: 1600,
    height: 800,
    title: "Link",
    shortCopy: "Connect to a record.",
    alt: "Tablet record card linking a code to NSN, document number, hand receipt, and photo.",
    caption: "Code linked to NSN, document number, hand receipt, and photo.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "how", "applications"],
    status: "concept",
    sourceTag: "BRIEF",
  },
  f: {
    id: "f",
    src: "images/panels/f-radio-readback.webp",
    width: 1600,
    height: 900,
    title: "Report",
    shortCopy: "Say code words when useful.",
    alt: 'Two radios with the handoff "Tag: copper, lantern, sky. Break." and a read-back.',
    caption: "Radio cue and read-back: three code words.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "how", "applications"],
    status: "concept",
    sourceTag: "BRIEF",
  },
  g: {
    id: "g",
    src: "images/panels/g-parcel.webp",
    width: 1600,
    height: 900,
    title: "Postal and parcel",
    shortCopy: "Handwritten code on a parcel.",
    alt: "Parcel with zz-river-maple-sky-zz handwritten beside the address.",
    caption: "Handwritten code on a parcel beside the address.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "applications"],
    status: "concept",
    sourceTag: "BRIEF",
  },
  h: {
    id: "h",
    src: "images/panels/h-lost-cat.webp",
    width: 1600,
    height: 902,
    title: "Everyday and community",
    shortCopy: "Lost-cat flyer.",
    alt: "Lost-cat flyer with zz-kathy-lost-cat-zz being scanned by a phone.",
    caption: "Lost-cat flyer with handwritten code.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "applications"],
    status: "concept",
    sourceTag: "BRIEF",
  },
  i: {
    id: "i",
    src: "images/panels/i-agent-alias.webp",
    width: 1600,
    height: 900,
    title: "Digital aliases",
    shortCopy: "Short agent alias.",
    alt: "Laptop showing a short zz alias mapped to a long agent address.",
    caption: "Short agent alias standing in for a long machine address.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "applications"],
    status: "concept",
    sourceTag: "BRIEF",
  },
  j: {
    id: "j",
    src: "images/panels/j-photo-to-action.webp",
    width: 1448,
    height: 1086,
    title: "Photograph",
    shortCopy: "Loose or broken items; spoken note.",
    alt: "Soldier photographing loose and broken items on a vehicle tailgate.",
    caption: "Loose or broken items; spoken note.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "how", "applications"],
    status: "concept",
    sourceTag: "WIRE",
  },
  k: {
    id: "k",
    src: "images/panels/k-ai-guidance.webp",
    width: 1448,
    height: 1086,
    title: "Guide",
    shortCopy: "Confirmed item and handling choices.",
    alt: "Rugged phone boxing each item with a proposed next step.",
    caption: "Confirmed item and handling choices.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "how", "applications", "demo"],
    status: "concept",
    sourceTag: "WIRE",
  },
  l: {
    id: "l",
    src: "images/panels/l-turn-in-form.webp",
    width: 1448,
    height: 1086,
    title: "Review",
    shortCopy: "Prepared form and photos.",
    alt: "Tablet turn-in request form with item fields and attached photos.",
    caption: "Prepared form and photos.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "how", "applications", "demo"],
    status: "concept",
    sourceTag: "WIRE",
  },
  m: {
    id: "m",
    src: "images/panels/m-shelf-inventory.webp",
    width: 1448,
    height: 1086,
    title: "Inventory assistant",
    shortCopy: "Same shelf across days.",
    alt: "Day 1 and Day 4 shelf photos; water at about two days left with a reorder prompt.",
    caption: "Same shelf across days; lower stock and proposed reorder.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "how", "applications"],
    status: "concept",
    sourceTag: "WIRE",
  },
  n: {
    id: "n",
    src: "images/panels/n-touch-first.webp",
    width: 1448,
    height: 1086,
    title: "Touch first",
    shortCopy: "Drag an identified item to an action.",
    alt: "Phone screen with a recognized item being dragged onto large action buttons.",
    caption: "Drag an identified item to an action; offer voice input.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "how", "applications"],
    status: "concept",
    sourceTag: "WIRE",
  },
  o: {
    id: "o",
    src: "images/panels/o-pack-and-ship.webp",
    width: 1448,
    height: 1086,
    title: "Pack and ship",
    shortCopy: "Packing guidance and parcel code.",
    alt: "Phone packing guidance for a guitar and an appliance with a zz parcel code.",
    caption:
      "Guitar and appliance packing guidance; handwritten zz parcel code.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "applications"],
    status: "concept",
    sourceTag: "BRIEF",
  },
  "demo-01": {
    id: "demo-01",
    src: "images/demo/01-crate-marked.webp",
    width: 1536,
    height: 1024,
    title: "Intro",
    shortCopy: "A field crate, marked by hand.",
    alt: "Field crate with a code handwritten on blue tape.",
    caption: "A field crate, marked by hand.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["demo"],
    status: "demo-mock",
    sourceTag: "ASSETS",
  },
  "demo-02": {
    id: "demo-02",
    src: "images/demo/02-crate-tape-closeup.webp",
    width: 1536,
    height: 1024,
    title: "Mark",
    shortCopy: "Write the code on tape.",
    alt: "Close-up of blue tape with a handwritten zz code.",
    caption: "Write the code on tape.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["demo"],
    status: "demo-mock",
    sourceTag: "ASSETS",
  },
  "demo-03": {
    id: "demo-03",
    src: "images/demo/03-crate-to-tablet.webp",
    width: 1536,
    height: 1024,
    title: "Linked",
    shortCopy: "Linked record (mock).",
    alt: "Marked crate beside a tablet showing its linked record.",
    caption: "Linked record (mock).",
    focal: { x: 0.5, y: 0.5 },
    destination: ["demo"],
    status: "demo-mock",
    sourceTag: "ASSETS",
  },
  "demo-04": {
    id: "demo-04",
    src: "images/demo/04-code-on-tablet-and-tape.webp",
    width: 1600,
    height: 800,
    title: "End",
    shortCopy: "Nothing was submitted.",
    alt: "The same zz code shown on a tablet screen and on tape.",
    caption: "Nothing was submitted.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["demo"],
    status: "demo-mock",
    sourceTag: "ASSETS",
  },
  "demo-05": {
    id: "demo-05",
    src: "images/demo/05-crate-handwritten-tape.webp",
    width: 1536,
    height: 1024,
    title: "Photo",
    shortCopy: "Photo taken (mock image).",
    alt: "Crate with a handwritten tape code, as photographed.",
    caption: "Photo taken (mock image).",
    focal: { x: 0.5, y: 0.5 },
    destination: ["demo"],
    status: "demo-mock",
    sourceTag: "ASSETS",
  },
  "hw-hackerdojo": {
    id: "hw-hackerdojo",
    src: "images/handwritten/zz-hackerdojo-zz.webp",
    width: 1050,
    height: 1400,
    title: "zz-hackerdojo-zz",
    shortCopy: "Real photo.",
    alt: "ZZ-HACKERDOJO-ZZ handwritten on paper.",
    caption: "Real photo.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["about"],
    status: "real-photo",
    sourceTag: "ASSETS",
  },
  "hw-helloworld": {
    id: "hw-helloworld",
    src: "images/handwritten/zz-helloworld-zz.webp",
    width: 1050,
    height: 1400,
    title: "zz-helloworld-zz",
    shortCopy: "Real photo.",
    alt: "ZZ-HELLOWORLD-ZZ handwritten on paper.",
    caption: "Real photo.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["about"],
    status: "real-photo",
    sourceTag: "ASSETS",
  },
  "hw-roto": {
    id: "hw-roto",
    src: "images/handwritten/zz-roto-zz.webp",
    width: 1050,
    height: 1400,
    title: "zz-roto-zz",
    shortCopy: "Real photo.",
    alt: "ZZ-ROTO-ZZ handwritten on paper.",
    caption: "Real photo.",
    focal: { x: 0.5, y: 0.5 },
    destination: ["about"],
    status: "real-photo",
    sourceTag: "ASSETS",
  },
  "logo-light": {
    id: "logo-light",
    src: "images/logos/zzthis-logo-on-light.webp",
    width: 464,
    height: 129,
    title: "zzThis",
    shortCopy: "zzThis",
    alt: "zzThis",
    caption: "",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "how", "applications", "about", "demo"],
    status: "logo",
    sourceTag: "ASSETS",
  },
  "logo-dark": {
    id: "logo-dark",
    src: "images/logos/zzthis-logo-on-dark.webp",
    width: 480,
    height: 140,
    title: "zzThis",
    shortCopy: "zzThis",
    alt: "zzThis",
    caption: "",
    focal: { x: 0.5, y: 0.5 },
    destination: ["home", "how", "applications", "about", "demo"],
    status: "logo",
    sourceTag: "ASSETS",
  },
} satisfies Record<string, ImageMeta>;

export type ImageId = keyof typeof images;
