// Writes src/generated/wordlists.ts from wordlists/*.txt, so the Worker and
// the web client bundle every list without reading files at run time (spec
// 005 plan, Bundled data). `npm run wordlists:module` then fails if the
// committed module drifted.
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dirname, "..");
const listDir = join(root, "wordlists");
const outDir = join(root, "src", "generated");

const entries = readdirSync(listDir)
  .filter((name) => name.endsWith(".txt"))
  .sort()
  .map((name) => {
    const words = readFileSync(join(listDir, name), "utf8").trimEnd();
    return `  ${JSON.stringify(name.slice(0, -4))}: ${JSON.stringify(words)},`;
  });

const source = [
  "// Generated by scripts/build-wordlists-module.ts from wordlists/*.txt.",
  "// Do not edit. Run npm run wordlists:module -w packages/zz-core.",
  "export const WORDLISTS = {",
  ...entries,
  "} satisfies Readonly<Record<string, string>>;",
  "",
].join("\n");

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "wordlists.ts"), source);
console.log(`wrote src/generated/wordlists.ts (${entries.length} lists)`);
